site_name: Augini Documentation
site_description: AI-Powered Tabular Data Augmentation Framework
site_author: Tabularis AI
repo_url: https://github.com/tabularis-ai/augini

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: quick-start.md
    - Provider Agnostic: provider-agnostic.md
  - APIs:
    - DataEngineer: data-engineer.md
    - DataAnalyzer: data-analyzer.md
    - Chat Interface: chat.md
  - Configuration: configuration.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tabularis-ai/augini
    - icon: fontawesome/brands/discord
      link: https://discord.gg/sznxwdqBXj
