site_name: Augini
site_url: https://tabularis-ai.github.io/augini/

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: blue
    - scheme: dark
      primary: indigo
      accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - toc.integrate
  logo: assets/images/logo_augini.png
extra: 
  social: 
  - icon: fontawesome/brands/discord 
    link: https://discord.gg/sznxwdqBXj