site_name: Augini Documentation
site_description: AI-Powered Tabular Data Augmentation Framework
site_author: Tabularis AI
repo_url: https://github.com/tabularis-ai/augini

theme:
  name: material
  logo: assets/images/logo_augini.png
  favicon: assets/images/favicon.ico
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - announce.dismiss

nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: quick-start.md
    - Provider Agnostic: provider-agnostic.md
  - APIs:
    - DataEngineer: data-engineer.md
    - DataAnalyzer: data-analyzer.md
    - Chat Interface: chat.md
  - Configuration: configuration.md
  - Privacy: privacy.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
      - manage
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tabularis-ai/augini
    - icon: fontawesome/brands/discord
      link: https://discord.gg/sznxwdqBXj
    - icon: fontawesome/brands/twitter
      link: https://x.com/tabularis_ai
    - icon: simple/huggingface
      link: https://huggingface.co/tabularisai

extra_css:
  - stylesheets/extra.css

copyright: >
  Copyright &copy; 2024 Tabularis AI –
  <a href="#__consent">Change cookie settings</a>
